name: pxt-buildpush

on:
  push:
    branches:
      - '**' # Run workflow when any branch is updated
    tags:
      - '*'  # Run workflow when any new tag is pushed

permissions:
  contents: write

jobs:
  filter-vtags:
    uses: ./.github/workflows/is-vtag.yml

  tag-bump-commit:
    uses: ./.github/workflows/tag-bump-commit.yml
    needs: filter-vtags
    if: needs.filter-vtags.outputs.is_vtag == false

  buildpush:
    name: buildpush
    runs-on: ubuntu-latest
    needs: tag-bump-commit
    if: always() && needs.tag-bump-commit.outputs.did_tag == false
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 18.x

      - name: npm install
        run: |
          sudo apt-get install xvfb
          sudo npm install -g pxt
          npm install

      - name: pxt ci (without publish capability)
        run: |
          pxt ci
        env:
          CHROME_BIN: chromium-browser
          DISPLAY: :99.0
          CI: true

  buildvtag:
    name: buildvtag
    runs-on: ubuntu-latest
    needs: tag-bump-commit
    if: always() && needs.tag-bump-commit.outputs.did_tag == true
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: 18.x

      - name: npm install
        run: |
          sudo apt-get install xvfb
          sudo npm install -g pxt
          npm install

      - name: pxt ci (with publish capability)
        run: |
          pxt ci
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          CHROME_BIN: chromium-browser
          DISPLAY: :99.0
          CI: true
